### ISSUE TITLE
More details about  choosed pre-trained detector and attribute classifier on Visual Genome dataset.

### ISSUE THREAD

**Issue by zaiquanyang** [LeapLabTHU/Pseudo-Q#1]
A good job. Can you provide more details about  choosed pre-trained detector and attribute classifier on Visual Genome dataset? Such as  download link or else.

**Comment by jianghaojun** [comment]
Thanks for your attention. I will try to release the pseudo-query generation code as soon as possible.

The pretrained detector and attribute classifier that we adopted are from this paper [Bottom-Up and Top-Down Attention for Image Captioning and Visual Question Answering](https://arxiv.org/abs/1707.07998).

You can use the pytorch implementation of this paper: [MILVLG/bottom-up-attention.pytorch](https://github.com/MILVLG/bottom-up-attention.pytorch) and
 [shilrley6/Faster-R-CNN-with-model-pretrained-on-Visual-Genome](https://github.com/shilrley6/Faster-R-CNN-with-model-pretrained-on-Visual-Genome).

**Comment by gicheonkang** [comment]
Hi, I have a question regarding this issue. 
The repositories you mentioned ([MILVLG/bottom-up-attention.pytorch](https://github.com/MILVLG/bottom-up-attention.pytorch) and [shilrley6/Faster-R-CNN-with-model-pretrained-on-Visual-Genome](https://github.com/shilrley6/Faster-R-CNN-with-model-pretrained-on-Visual-Genome)) yield numpy files, but your code reads the results as ".pth" files in [here](https://github.com/LeapLabTHU/Pseudo-Q/blob/main/pseudo_sample_generation/pseudo_query_generation.py). I think there should be a preprocessing code to make it compatible. Can you share more details? Thanks!
