### ISSUE TITLE
您好，请问您可视化pseudo sample 的脚本有添加在github中吗？About visualizing the pseudo samples.

### ISSUE THREAD

**Issue by HB-pencil-zero** [LeapLabTHU/Pseudo-Q#12]

**Comment by jianghaojun** [comment]
The bbox or the pseudo-query?

**Comment by jianghaojun** [comment]
I didn't add the visualization code yet. If you want to visualize the bbox, you can follow the code [here](https://github.com/shilrley6/Faster-R-CNN-with-model-pretrained-on-Visual-Genome/blob/2a56c13c4855c5b9337b62ad15a67f316a81f73f/demo.py#L359-L364). 

@HB-pencil-zero I will close this question if there are no more questions.
