### ISSUE TITLE
A work (RSVG) that is very similar to yours but did not cite your work. 

### ISSUE THREAD

**Issue by linhuixiao** [LeapLabTHU/Pseudo-Q#13]
Hi, I found a work (https://github.com/ZhanYang-nwpu/RSVG-pytorch) that is very similar to yours but did not cite your work. 

1. the method of constructing pseudo labels of remote sensing data
2. MLCF (Multi-level Cross-modal Fusion) mentioned in RSVG

you can pay attention to it.

**Comment by jianghaojun** [comment]
@linhuixiao Thanks so much for sharing this information with me! I will check the paper and compare the technical details!
