### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by JayLee175** [LeapLabTHU/Pseudo-Q#14]
Sorry for bothering.When i run the train.py , something went wrong. Here is the output imformation:

E:\Users\JayLee\anaconda3\envs\myenv\python.exe E:/Pseudo-Q-main/train.py
Not using distributed mode
git:
  sha: N/A, status: clean, branch: N/A

### INFO ### torch.backends.cudnn.benchmark = False
number of params: 155559940
Missing keys when loading detr model:
[]
Start training
E:\Users\JayLee\anaconda3\envs\myenv\lib\site-packages\torch\nn\functional.py:718: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ..\c10/core/TensorImpl.h:1156.)
  return torch.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
E:\Users\JayLee\anaconda3\envs\myenv\lib\site-packages\torch\_tensor.py:575: UserWarning: floor_divide is deprecated, and will be removed in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values.
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  ..\aten\src\ATen\native\BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
Traceback (most recent call last):
  File "E:\Pseudo-Q-main\train.py", line 310, in <module>
    main(args)
  File "E:\Pseudo-Q-main\train.py", line 265, in main
    train_stats = train_one_epoch(
  File "E:\Pseudo-Q-main\engine.py", line 38, in train_one_epoch
    output = model(img_data, text_data)
  File "E:\Users\JayLee\anaconda3\envs\myenv\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Pseudo-Q-main\models\trans_vg_mlcma.py", line 36, in forward
    visu_mask, visu_src = self.visumodel(img_data)
  File "E:\Users\JayLee\anaconda3\envs\myenv\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Pseudo-Q-main\models\visual_model\detr.py", line 72, in forward
    out = self.transformer(self.input_proj(src), mask, pos[-1], query_embed=None)
  File "E:\Users\JayLee\anaconda3\envs\myenv\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Pseudo-Q-main\models\visual_model\transformer.py", line 56, in forward
    memory = self.encoder(src, src_key_padding_mask=mask, pos=pos_embed)
  File "E:\Users\JayLee\anaconda3\envs\myenv\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Pseudo-Q-main\models\visual_model\transformer.py", line 118, in forward
    output = layer(output, src_mask=mask,
  File "E:\Users\JayLee\anaconda3\envs\myenv\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Pseudo-Q-main\models\visual_model\transformer.py", line 225, in forward
    return self.forward_post(src, src_mask, src_key_padding_mask, pos)
  File "E:\Pseudo-Q-main\models\visual_model\transformer.py", line 196, in forward_post
    src2 = self.self_attn(q, k, value=src, attn_mask=src_mask,
  File "E:\Users\JayLee\anaconda3\envs\myenv\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Users\JayLee\anaconda3\envs\myenv\lib\site-packages\torch\nn\modules\activation.py", line 1031, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "E:\Users\JayLee\anaconda3\envs\myenv\lib\site-packages\torch\nn\functional.py", line 4969, in multi_head_attention_forward
    q, k, v = _in_projection_packed(query, key, value, in_proj_weight, in_proj_bias)
  File "E:\Users\JayLee\anaconda3\envs\myenv\lib\site-packages\torch\nn\functional.py", line 4734, in _in_projection_packed
    return linear(q, w_q, b_q), linear(k, w_k, b_k), linear(v, w_v, b_v)
  File "E:\Users\JayLee\anaconda3\envs\myenv\lib\site-packages\torch\nn\functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: CUDA error: CUBLAS_STATUS_ALLOC_FAILED when calling `cublasCreate(handle)`

进程已结束,退出代码1

I don't know how to fix it. Could you please help and give me some ideas? Thank you!

**Comment by jianghaojun** [comment]
Hi, after searching the error info in google, I found a [suggestion](https://stackoverflow.com/questions/61473330/cuda-error-cublas-status-alloc-failed-when-calling-cublascreatehandle#:~:text=This%20error%20can%20actually%20be%20due%20to%20different%20reasons.%20It%20is%20recommended%20to%20debug%20CUDA%20errors%20by%20running%20the%20code%20on%20the%20CPU%2C%20if%20possible.%20If%20that%E2%80%99s%20not%20possible%2C%20try%20to%20execute%20the%20script%20via%3A) that might be worth a try.

It would be better to provide more informations about your hardware and training settings.

Btw, this issue #7 contains some instructions about training.

**Comment by JayLee175** [comment]
我还是无法解决该问题，硬件和训练设置都没有问题，如各种库的版本（torch……），cuda和cudnn的版本也都符合电脑显卡所支持的版本，环境配置也没有问题。我始终找不出原因。

I still can't solve the problem, the hardware and training settings are fine, such as the versions of the various libraries (torch ......), the versions of cuda and cudnn all match the versions supported by the computer's graphics card, and the environment configuration is fine. I could never find the cause.

**Comment by JayLee175** [comment]
我看有一个办法是改用cpu运行代码以找出错误，请问怎么用cpu运行而不是gpu。

I see that there is a way to run the code on cpu instead to find the error, how can I run it on cpu instead of gpu please.

**Comment by jianghaojun** [comment]
> 我看有一个办法是改用cpu运行代码以找出错误，请问怎么用cpu运行而不是gpu。

Try this one from the [suggestion](https://stackoverflow.com/questions/61473330/cuda-error-cublas-status-alloc-failed-when-calling-cublascreatehandle#:~:text=This%20error%20can%20actually%20be%20due%20to%20different%20reasons.%20It%20is%20recommended%20to%20debug%20CUDA%20errors%20by%20running%20the%20code%20on%20the%20CPU%2C%20if%20possible.%20If%20that%E2%80%99s%20not%20possible%2C%20try%20to%20execute%20the%20script%20via%3A).

```
CUDA_LAUNCH_BLOCKING=1 python [YOUR_PROGRAM]
```

BTW, could you try to run the code on a Linux system instead of Windows?

**Comment by JayLee175** [comment]
我暂时没有安装Linux

**Comment by JayLee175** [comment]
感谢！当我尝试让程序只用cpu运行时，就开始训练了，但是速度极其的缓慢。看来确实是CUDA某个地方出了错误，我将继续尝试。

Thanks! When I tried to get the program to run on cpu only, it started training, but it was extremely slow. It does seem to be a CUDA error somewhere, I will keep trying.

**Comment by JayLee175** [comment]
还有一个问题，就是之前运行train.py的时候，显示没有detr-r50.pth模型，所以我自己在网上下的一个。这样是对的嘛？

One more question is that when I ran train.py before, it showed that there was no detr-r50.pth model, so I downloaded one myself from the internet. Is this correct?

**Comment by jianghaojun** [comment]
> 感谢！当我尝试让程序只用cpu运行时，就开始训练了，但是速度极其的缓慢。看来确实是CUDA某个地方出了错误，我将继续尝试。
> 
> Thanks! When I tried to get the program to run on cpu only, it started training, but it was extremely slow. It does seem to be a CUDA error somewhere, I will keep trying.

Glad to hear that. Please share the solution if you resolve this bug. It would be helpful for others.

> 还有一个问题，就是之前运行train.py的时候，显示没有detr-r50.pth模型，所以我自己在网上下的一个。这样是对的嘛？
> 
> One more question is that when I ran train.py before, it showed that there was no detr-r50.pth model, so I downloaded one myself from the internet. Is this correct?

The ckpt can be downloaded from [here](https://github.com/LeapLabTHU/Pseudo-Q#:~:text=Pretrained%20Checkpoints).

**Comment by jianghaojun** [comment]
@JayLee175 Did you solve the problem？

**Comment by jianghaojun** [comment]
Closed.
