### ISSUE TITLE
关于生成伪标注的问题 Regarding the Issue of Generating Pseudo-label

### ISSUE THREAD

**Issue by huijiang2486** [LeapLabTHU/Pseudo-Q#18]
请问您在生成伪标注时，针对不同的数据集是否使用了不同的方法或超参？我注意到refcoco和refcoco+生成的伪标注数量相差很大，但refcoco和refcoco+包含的图片数量似乎相差并不大。

Could you please tell me if you used different methods or hyperparameters when generating pseudo-label for different datasets? I have noticed that the number of pseudo-label generated for refcoco and refcoco+ differs significantly, but the number of images contained in refcoco and refcoco+ seems to be quite similar.

**Comment by jianghaojun** [comment]
Please see the implementation details in the experimental section.

**Comment by jianghaojun** [comment]
Closed.
