### ISSUE TITLE
作者您好，请问能不能对数据集目录部分描述再详细一点，谢谢。Could author provide more detailed descriptions about the dataset folder？

### ISSUE THREAD

**Issue by linhuixiao** [LeapLabTHU/Pseudo-Q#2]
```angular2html
|-- image_data
   |-- data
      |-- flickr
      |-- gref
      |-- gref_umd
      |-- referit
      |-- unc
      |-- unc+
   |-- Flickr30k
      |-- flickr30k-images
   |-- other
      |-- images
      |-- refcoco
      |-- refcoco+
      |-- refcocog
   |-- referit
      |-- images
      |-- mask
      |-- splits
```

上述 Readme 部分提供的数据集目录结构，只是简单罗列，而且很多都有出入未说明。''other'' 目录应该是指 原始 ''refer'' 仓库的文件吧？ 另外，''data'' 目录应该是指下载的 ''pseudo_samples'' 吧？ 然后 ''referit'' 文件目录有点莫名其妙不太理解，原始的 ''refer'' 里面是 ''ReCLEF''，但是目录下面的 ‘’images, mask, splits‘’ 未查到，请问这个referit 目录又该怎么构建？？
谢谢！

**Comment by jianghaojun** [comment]
I apologize for the unclear description. Let me make it more clear.

- **./data/image_data/data/xxx/**: Take the Flickr30K dataset as an example, ./data/image_data/data/flickr/ shoud contain files about the dataset's validation/test annotations(bbox-query pairs download from [Gdrive](https://drive.google.com/file/d/1fVwdDvXNbH8uuq_pHD_o5HI7yqeuz0yS/view?usp=sharing)) and our generated pseudo-annotations(pseudo-samples) for this dataset. You should uncompress the provided pseudo-sample files and put them on the corresponding folder.
- **./data/image_data/Flickr30k/flickr30k-images/**: Image data for the Flickr30K dataset, please download from this [link](http://shannon.cs.illinois.edu/DenotationGraph/#:~:text=make%20face-,Downloads,-Please%20fill%20in). Fill the form and download the images.
- **./data/image_data/other/images/**: Image data for RefCOCO/RefCOCO+/RefCOCOg.
- **./data/image_data/referit/images/**: Image data for ReferItGame.
- ./data/image_data/other/refcoco/, ./data/image_data/other/refcoco+/, ./data/image_data/other/refcocog/, ./data/image_data/referit/mask/, ./data/image_data/referit/splits/: I follow the TransVG to prepare the data and I find these folders actually are not used in training.

I notice the links of refcoco/refcoco+/refcocog/referit data are not available recently.  **You can leave an email here and I will send a download link to you**(I am not allowed to provide a public link here since the copyright issue).

**Comment by linhuixiao** [comment]
linhui.xiao@foxmail.com,   thanks a lot!

**Comment by nozomu-karai** [comment]
karai.nozomu.77c@st.kyoto-u.ac.jp

**Comment by jianghaojun** [comment]
> [karai.nozomu.77c@st.kyoto-u.ac.jp](mailto:karai.nozomu.77c@st.kyoto-u.ac.jp)

Hi, I send an email to you. Please leave a STAR ⭐ if this project help your research!

**Comment by jerry0805** [comment]
jerry0805@gmail.com , thanks

**Comment by jianghaojun** [comment]
> [jerry0805@gmail.com](mailto:jerry0805@gmail.com) , thanks

Hi, I send an email to you. Please leave a STAR ⭐ if this project help your research!

**Comment by xpwu95** [comment]
@jianghaojun Great work! Please send the data link to 'xpwu95@163.com', best!

**Comment by jianghaojun** [comment]
> @jianghaojun Great work! Please send the data link to '[xpwu95@163.com](mailto:xpwu95@163.com)', best!

@xpwu95 Hi, I send an email to you.

**Comment by Carlofkl** [comment]
Please send the data link to '[carlo_fkl@163.com](mailto:carlo_fkl@163.com)', thanks a lot!

**Comment by jianghaojun** [comment]
> Please send the data link to '[carlo_fkl@163.com](mailto:carlo_fkl@163.com)', thanks a lot!

@Carlofkl Hi, I send an email to you. Please leave a STAR ⭐ if this project help your research!

**Comment by jinxiao22** [comment]
Please send the data link to 'jinxiao9922@163.com', thanks a lot!

**Comment by jianghaojun** [comment]
> Please send the data link to '[jinxiao9922@163.com](mailto:jinxiao9922@163.com)', thanks a lot!

@jinxiao22 Hi, I send an email to you. Please leave a STAR ⭐ if this project help your research!

**Comment by hou-yz** [comment]
Hi could you please send me a download link to this email address? Thanks in advance!
hou_yz@outlook.com

**Comment by jianghaojun** [comment]
@hou-yz Hi, I send an email to you.

**Comment by 123-sweatheart** [comment]
Please send the data link to '[nwulxn@163.com](mailto:nwulxn@163.com)', thanks a lot!

**Comment by jianghaojun** [comment]
> Please send the data link to '[nwulxn@163.com](mailto:nwulxn@163.com)', thanks a lot!

@123-sweatheart Hi, I send an email to you.

**Comment by dneirfi** [comment]
Hi, please send the data link to 'dneirfi@korea.ac.kr'. Thanks a lot :)

**Comment by jianghaojun** [comment]
@dneirfi Hi, I send an email to you.

> Hi, please send the data link to '[dneirfi@korea.ac.kr](mailto:dneirfi@korea.ac.kr)'. Thanks a lot :)

**Comment by martin3436** [comment]
Please send the data link to 'martin3436@yeah.net', thanks a lot!

**Comment by jianghaojun** [comment]
> Please send the data link to '[martin3436@yeah.net](mailto:martin3436@yeah.net)', thanks a lot!

@martin3436 Hi, I send an email to you.

**Comment by ITlady-yyx** [comment]
请将数据链接发送至'[yangyunxia62@gmail.com](mailto:yangyunxia62@gmail.com)'，非常感谢！

**Comment by AngelYang23** [comment]
Please send the data link to '[yangyunxia62@gmail.com](mailto:yangyunxia62@gmail.com)', thanks a lot!

**Comment by jianghaojun** [comment]
> Please send the data link to '[yangyunxia62@gmail.com](mailto:yangyunxia62@gmail.com)', thanks a lot!

@ITlady-yyx  I resend the links from gmail to you, please check the email.

**Comment by zhaowangzs** [comment]
Please send the data link to 'xsjkhlala@163.com', thanks a lot!

**Comment by jianghaojun** [comment]
@zhaowangzs Hi, I send it to you. Please check your email.

**Comment by fawnliu** [comment]
Please send the data to '[wedkowasx@outlook.com](wedkowasx@outlook.com)', thanks a lot!

**Comment by jianghaojun** [comment]
> Please send the data to '[wedkowasx@outlook.com](wedkowasx@outlook.com)', thanks a lot!

@scarleatt Hi, I send it to you. Please check your email.

**Comment by pqviet** [comment]
Please send the data link to 'vietvn82@gmail.com', thanks a lot.

**Comment by jianghaojun** [comment]
@pqviet Hi, I send it to you. Please check your email.

**Comment by ZhanYang-nwpu** [comment]
Could you please provide the data link? Thank you very much!   “zhanyang@mail.nwpu.edu.cn”

**Comment by jianghaojun** [comment]
@ZhanYang-nwpu Hi, I send it to you. Please check your email. Please leave a STAR ⭐ if this project helps your research!

**Comment by TungWg** [comment]
Please send the link to zarath_xuany@163.com, thanks!

**Comment by jianghaojun** [comment]
@TungWg Hi, I send it to you. Please check your email. Please leave a STAR ⭐ if this project helps your research!

**Comment by TungWg** [comment]
Hi, Jiang Haojun, thanks for your prompt reply. I have already starred your work, but I can't find the link.



At 2022-11-14 11:47:10, "Jiang Haojun" ***@***.***> wrote:

@TungWg Hi, I send it to you. Please check your email. Please leave a STAR ⭐ if this project helps your research!

**Comment by HB-pencil-zero** [comment]
huangbei@stu.pku.edu.cn   ,麻烦您给我的邮件发送一份，谢谢！

**Comment by jianghaojun** [comment]
@HB-pencil-zero Hi, I send it to you. Please check your email.

**Comment by Eric-Chen-L** [comment]
Could you please provide the data link? Thank you very much! I have given you a Star for your work. My email is“ ericchenl@163.com"

**Comment by jianghaojun** [comment]
@Eric-Chen-L Hi, I send it to you. Please check your email.

**Comment by chenwei746** [comment]
weichencs@whu.edu.cn, Thanks!

**Comment by jianghaojun** [comment]
@chenwei746 Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!.

**Comment by Jumpy-pku** [comment]
Please send a data link to "hcg@pku.edu.cn", thank you very much

**Comment by jianghaojun** [comment]
@Jumpy-pku Hi, I send it to you. Please check your email.

**Comment by GuXiaohan241** [comment]
> ```
> |-- image_data
>    |-- data
>       |-- flickr
>       |-- gref
>       |-- gref_umd
>       |-- referit
>       |-- unc
>       |-- unc+
>    |-- Flickr30k
>       |-- flickr30k-images
>    |-- other
>       |-- images
>       |-- refcoco
>       |-- refcoco+
>       |-- refcocog
>    |-- referit
>       |-- images
>       |-- mask
>       |-- splits
> ```
> 
> 上述 Readme 部分提供的数据集目录结构，只是简单罗列，而且很多都有出入未说明。''other'' 目录应该是指 原始 ''refer'' 仓库的文件吧？ 另外，''data'' 目录应该是指下载的 ''pseudo_samples'' 吧？ 然后 ''referit'' 文件目录有点莫名其妙不太理解，原始的 ''refer'' 里面是 ''ReCLEF''，但是目录下面的 ''images， mask， splits'' 未查到，请问这个referit 目录又该怎么构建？？ 谢谢！

**Comment by GuXiaohan241** [comment]
您好，我的邮箱是snow_xiao30@163.com，麻烦您提供一份数据链接了，感谢！

**Comment by GuXiaohan241** [comment]
please send me the link to snow_xiao30@163.com,thank you !

**Comment by jianghaojun** [comment]
@GuXiaohan241 Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!

**Comment by xianglinbuaa** [comment]
xlinbuaa@163.com 麻烦您给我发一份，谢谢了！

**Comment by jianghaojun** [comment]
@xianglinbuaa Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!

**Comment by drigoni** [comment]
Hi, may I have the features and bounding boxes for Referit extracted with the object detector? davide.rigoni.2@phd.unipd.it

**Comment by jianghaojun** [comment]
@drigoni Hi, the detection results for Referit are provided [here](https://github.com/LeapLabTHU/Pseudo-Q/tree/main/pseudo_sample_generation#:~:text=You%20can%20download%20the%20detection%20results%20from%20Google%20Drive%20and%20put%20them%20in%20the%20right%20place.). Please leave a STAR ⭐ if this project helps your research!

**Comment by seokwon99** [comment]
Hi, please send the data link to 'seokwon1999@gmail.com'. Thank you!

**Comment by jianghaojun** [comment]
@seokwon99 Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!

**Comment by haibin-chen** [comment]
Hello, please send the data link to '[haibin_chen@foxmail.com](mailto:haibin_chen@foxmail.com)'. I have given you a star~ Thank you!

**Comment by jianghaojun** [comment]
@haibin-chen Hi, I send it to you. Please check your email.

**Comment by lszw11** [comment]
Hi, please send a data link to 'qq851256089@163.com', thanks a lot!

**Comment by jianghaojun** [comment]
@lszw11 Hi, I send it to you. Please check your email.

**Comment by JayLee175** [comment]
Hi, please send a data link to 'zhongguodiao175@gmail.com',  thanks a lot!峻哥，麻烦给我也发一份，迫切需要。万分感谢！

**Comment by jianghaojun** [comment]
@JayLee175 Bro, I send it to you. Please check your email.

**Comment by jianghaojun** [comment]
CLOSED.

**Comment by huijiang2486** [comment]
麻烦也给我发一份数据，万分感谢！！jianghui.email@qq.com

**Comment by jianghaojun** [comment]
@huijiang2486 Hi, I send it to you. Please check your email.

**Comment by BubbleSai** [comment]
Hi, please send a data link to xvcksai@163.com ,  thanks a lot!

**Comment by qzy1233** [comment]
Hi, please send a data link to qzywd666@163.com , thanks a lot!

**Comment by jianghaojun** [comment]
@BubbleSai @qzy1233 Hi, I send it to you guys. Please check your email.

**Comment by Ykpypl** [comment]
ykp0613@163.com, thanks a lot!

**Comment by jianghaojun** [comment]
@AAAAlexing Hi, I send it to you guys. Please check your email.

**Comment by Marloweeee** [comment]
lhb2022@foxmail.com, thanks a lot!

**Comment by jianghaojun** [comment]
@Marloweeee Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!

**Comment by Marloweeee** [comment]
Thanks very much for your help, I have already STAR&FORK this project. But please resend the link to lihb@foxmail.com, because I accidentally typed in the wrong email. Thanks again!!!

**Comment by Marloweeee** [comment]
> @Marloweeee Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!

Thanks very much for your help, I have already STAR&FORK this project. But please resend the link to [lihb2022@foxmail.com](mailto:lihb2022@foxmail.com), because I accidentally typed in the wrong email. Thanks again!!!

**Comment by jianghaojun** [comment]
@Marloweeee Resent the link to the new email.

**Comment by XiaokunFeng** [comment]
Please send the data link to '[fengxiaokun1999@163.com](mailto:fengxiaokun1999@163.com)', thanks a lot!

**Comment by jianghaojun** [comment]
@XiaokunFeng Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!

**Comment by XiaokunFeng** [comment]
Copy that！Thanks！
---- 回复的原邮件 ----
| 发件人 | Haojun ***@***.***> |
| 发送日期 | 2023年07月25日 16:59 |
| 收件人 | LeapLabTHU/Pseudo-Q ***@***.***> |
| 抄送人 | XiaokunFeng ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [LeapLabTHU/Pseudo-Q] 作者您好，请问能不能对数据集目录部分描述再详细一点，谢谢。Could author provide more detailed descriptions about the dataset folder？ (Issue #2) |

@XiaokunFeng Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!

**Comment by Nikol-coder** [comment]
您好，请问能麻烦您给我分享一份数据集吗？万分感谢！！ 特别是referit 的数据集

**Comment by Nikol-coder** [comment]
您好，请问能麻烦您给我分享一份数据集吗？万分感谢！！ 特别是referit 的数据集，我的邮箱是"1069812938@qq.com"

**Comment by jianghaojun** [comment]
@Nikol-coder Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!

**Comment by Shoko071** [comment]
您好，请问能麻烦您给我分享一份数据集吗？万分感谢！！ 我的邮箱是csyfliu@foxmail.com

**Comment by Nikol-coder** [comment]
下载地址：https://cloud.tsinghua.edu.cn/f/b2c4278671554d699140/?dl=1&nbsp; &nbsp; ，不用翻墙




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LeapLabTHU/Pseudo-Q"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月12日(星期二) 下午5:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LeapLabTHU/Pseudo-Q] 作者您好，请问能不能对数据集目录部分描述再详细一点，谢谢。Could author provide more detailed descriptions about the dataset folder？ (Issue #2)





 
您好，请问能麻烦您给我分享一份数据集吗？万分感谢！！ ***@***.***

**Comment by jianghaojun** [comment]
@Shoko071 Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!

@Nikol-coder Thank you for your prompt response!

**Comment by zmingshu** [comment]
zms1301688491@163.com万分感谢

**Comment by jianghaojun** [comment]
@zmingshu Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!

**Comment by zmingshu** [comment]
> 下载地址：[https://cloud.tsinghua.edu.cn/f/b2c4278671554d699140/?dl=1](https://cloud.tsinghua.edu.cn/f/b2c4278671554d699140/?dl=1&nbsp) ;   ，不用翻墙
> [……](#)
> ------------------ 原始邮件 -------------------- 发件人: "LeapLabTHU/Pseudo -Q"***@***.***>; 发送时间： 2023年9月12日(星期二)下午5:15 ***@***.***>; **@***.******@***.***>; 主题: 回复：[LeapLabTHU/Pseudo-Q]作者您好，请问不能对数据集目录部分描述再详细一点，谢谢。作者可以提供有关数据集文件夹的更详细描述吗？（问题 #2 [）](https://github.com/LeapLabTHU/Pseudo-Q/issues/2)您好，请问能否麻烦您给我分享一份数据集吗？万分感谢！！ ***@***.*** — 直接回复此电子邮件，在 GitHub 上查看它，或取消订阅。您收到此消息是因为您被提及。消息 ID：***@***.***>

你好，请问一下RefCOCO、RefCOCO+、RefCOCOg序列里面本身就是没有图片的吗

**Comment by zmingshu** [comment]
请问一下RefCOCO、RefCOCO+、RefCOCOg序列里面本身就是没有图片的吗

**Comment by jianghaojun** [comment]
I do not own the data, so making the data link public may lead to copyright issues. Please do not make it public in this repository.

**Comment by jianghaojun** [comment]
> 请问一下RefCOCO、RefCOCO+、RefCOCOg序列里面本身就是没有图片的吗

这里的“序列”是指什么？

**Comment by zmingshu** [comment]
> > 请问一下RefCOCO、RefCOCO+、RefCOCOg序列里面本身就是没有图片的吗
> 
> 这里的“序列”是指什么？

就是RefCOCO、RefCOCO+、RefCOCOg文件夹下面只有.json和.p文件，没有图片吗

**Comment by jianghaojun** [comment]
> > > 请问一下RefCOCO、RefCOCO+、RefCOCOg序列里面本身就是没有图片的吗
> > 
> > 
> > 这里的“序列”是指什么？
> 
> 就是RefCOCO、RefCOCO+、RefCOCOg文件夹下面只有.json和.p文件，没有图片吗

在 images 里

**Comment by SudaYDD** [comment]
Hi, please also send me a data link, thanks a lot!![gouchenyi0721@163.com](mailto:gouchenyi0721@163.com)

**Comment by kingjack12345** [comment]
please also send me a data link, thanks a lot!zhuw6075@gmail.com

**Comment by jianghaojun** [comment]
@kingjack12345 Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!

**Comment by Wiikk** [comment]
Hi, could you please send me a data link, thanks!  yikewu1@gmail.com

**Comment by jianghaojun** [comment]
@Wiikk Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!

**Comment by yangaonidaye123** [comment]
Hi, could you please send me a data link, thanks！770887851@qq.com

**Comment by jianghaojun** [comment]
@yangaonidaye123 Hi, I send it to you. Please check your email and leave a STAR ⭐ if this project helps your research!

**Comment by lxixim** [comment]
Hi, could you please send me a data link, thanks！lxixixxxm@gmail.com

**Comment by zy845047842** [comment]
Hi, could you please send me a referit data link, thanks！zy845047842@gmail.com

**Comment by haolan0427** [comment]
Hi, could you please send me a data link, thanks! xuhaolan0427@gmail.com
