### ISSUE TITLE
extract_utils.py文件缺失

### ISSUE THREAD

**Issue by peach-xiao** [LeapLabTHU/Pseudo-Q#20]
作者您好！在认真阅读了论文后，我想要按照说明尝试生成伪区域-查询对，仔细查看了get_detection_results.py，发现在导入这个get_image_blob模块的时候，好像没有这个文件，请问可以提供这个utils.extract_utils.py文件吗？

![image](https://github.com/user-attachments/assets/138af525-6b0c-49df-b96f-5b310aaab62b)

**Comment by jianghaojun** [comment]
已添加到 pseudo_sample_generation/utils 下了
