### ISSUE TITLE
如何生成伪样本? How to generate pseudo sample?

### ISSUE THREAD

**Issue by peach-xiao** [LeapLabTHU/Pseudo-Q#21]
作者您好！这篇论文的工作做的很优秀。我希望通过提供的代码生成数据集中的为伪样本，在这个过程中遇到了很多困难，实在是没有解决，真诚的希望您能够提供一些帮助

1. 我在尝试使用您提供的get_detection_results.py文件生成伪样本，但是这个文件中导入了nms和add_bottom_up_attention_config两个函数，
from models.bua.ayers.nms import nms    ### The import file is here: https://github.com/MILVLG/bottom-up-attention.pytorch/blob/master/bua/caffe/modeling/layers/nms.py
from models.bua import add_bottom_up_attention_config

我从注释提供的代码连接中去找nms.py文件，其中有from models.bua.caffe.modeling import _C，这涉及到了需要编译的问题，直接运行get_detection_results.py生成伪代码是不行的。

2.然后我尝试去这个链接 https://github.com/MILVLG/bottom-up-attention.pytorch 下载完整的代码编译，并期待能够成功运行get_detection_results.py生成伪样本，但是按照这个作者的说明，需要安装 v0.2.1版本的Detectron2

![image](https://github.com/user-attachments/assets/429e69c1-1909-4a82-9f6c-cd305a79da8f)

然后又出现了问题， v0.2.1版本的Detectron2最高支持torch1.6，虽然成功安装，但是torch的版本太低，导致代码出现问题也不能运行
![image](https://github.com/user-attachments/assets/8d2d1ddf-157c-46b5-ad61-c4b9ad8cca48)

然后我又去装v0.5版本的Detectron2，因为这个[bottom-up-attention.pytorch](https://github.com/MILVLG/bottom-up-attention.pytorch)是基于 v0.2.1版本的Detectron2写的代码，最后还是不能运行。
![image](https://github.com/user-attachments/assets/f4df953b-e169-4d8b-88cc-db7e82d4b5c6)

在尝试生成伪样本的过程中，要么是版本冲突，要么是现有版本不支持部分代码，因此现在也没能够解决如何生成伪样本的问题，作者您看到了以后可以提供一份可运行的代码给我吗？这对我非常有帮助，期待您的回复

**Comment by jianghaojun** [comment]
目标检测用什么模型都可以，之前基于 botten-up-attention 获得的目标检测结果可以从 [Link](https://drive.google.com/file/d/1rC2TEnLlQe-URGRh5_rpmGGExvQDFcZV/view?usp=sharing) 下载。

有了目标检测结果就可以用 [pseudo_query_generation.py](https://github.com/LeapLabTHU/Pseudo-Q/blob/main/pseudo_sample_generation/pseudo_query_generation.py) 去生成伪样本。

Any model can be used for target detection. The target detection results previously obtained based on botten-up-attention can be downloaded from [Link](https://drive.google.com/file/d/1rC2TEnLlQe-URGRh5_rpmGGExvQDFcZV/view?usp=sharing).

With the target detection results, you can use [pseudo_query_generation.py](https://github.com/LeapLabTHU/Pseudo-Q/blob/main/pseudo_sample_generation/pseudo_query_generation.py) to generate pseudo samples.
