### ISSUE TITLE
can't find build_model 

### ISSUE THREAD

**Issue by insundaycathy** [LeapLabTHU/Pseudo-Q#4]
Hey, I can't the fing the code for build_model in the models folder. which .py file is it in?

**Comment by jianghaojun** [comment]
Hi @insundaycathy, the build_model function is in the following code:
https://github.com/LeapLabTHU/Pseudo-Q/blob/6c372efd9b04185faf26fa762bc7f5a6404296f9/models/__init__.py#L1-L5
