### ISSUE TITLE
Unable to download the faster RCNN results

### ISSUE THREAD

**Issue by hou-yz** [LeapLabTHU/Pseudo-Q#5]
Hi, thank you for your work!

I cannot download the 'detection_results.tar.gz' file following the instructions [here](https://github.com/LeapLabTHU/Pseudo-Q/blob/6c372efd9b04185faf26fa762bc7f5a6404296f9/pseudo_sample_generation/README.md?plain=1#L8). Is that a server issue? Can you please provide other download sources?

Best,
Yunzhong

**Comment by hou-yz** [comment]
The download always freezes after 157.89M download. Have this issue on multiple devices.

**Comment by jianghaojun** [comment]
@hou-yz Hi, sorry for the download problem. Here is a download link from [Google Drive](https://drive.google.com/file/d/148yX36rLXNFZysop6PlP0XUKmQB3PSqT/view?usp=sharing). 

Feel free to contact me if you still have any other problem!
