### ISSUE TITLE
Evaluation on RefCOCO

### ISSUE THREAD

**Issue by dneirfi** [LeapLabTHU/Pseudo-Q#6]
Hi. Thanks to sharing your nice work!

When I run eval.sh on RefCOCO testA, I got the error "No such file unc_testA.pth'.
I wonder Why unc_testA.pth file is needed during evaluation? 

I also run generate_pseudo_data_unc.sh before evaluation and I got unc_train_pseudo_split.pth files, not unc_pseudo_val.pth or unc_pseudo_testA.pth.

Thanks.

**Comment by jianghaojun** [comment]
The eval.sh is provided to reproduce the results reported in the paper. For RefCOCO, we report the results on val/testA/testB splits.

We need to evaluate the performance on the manually annotated val/test for fair comparison with other methods. Thus, the pseudo samples are only used in training.

You can download the manually annotated val/test from this [link](https://drive.google.com/file/d/1fVwdDvXNbH8uuq_pHD_o5HI7yqeuz0yS/view).

**Comment by dneirfi** [comment]
Then, unc_testA.pth, unc_testB.pth, unc_val.pth files mean the manually annotated val/test datasets?  

Also, I try to reproduce the results on RefCOCO+, RefCOCOg and other datasets. 
How can I get the unc+_train_imagelist_split.txt files?

**Comment by jianghaojun** [comment]
Yes, val/testA/testB are manually annotated which are original data from each dataset. The pseudo samples are only used in training.

The download link for detection results and unc+_train_imagelist_split.txt files are already provided in the [README.md](https://github.com/LeapLabTHU/Pseudo-Q/blob/main/pseudo_sample_generation/README.md#:~:text=You%20can%20download%20the%20detection%20results%20from%20Google%20Drive%20and%20put%20them%20in%20the%20right%20place.).

**Comment by dneirfi** [comment]
Oh, I got it. 
Thanks for your quick reply!
