### ISSUE TITLE
statistics of datasets

### ISSUE THREAD

**Issue by TungWg** [LeapLabTHU/Pseudo-Q#8]
Hi, thank you for your excellent work! I found that /data/statistic/ did not have the .txt split files of other datasets. Is there any way to access these files?

**Comment by TungWg** [comment]
I've found them, I'm going to close this issue.

**Comment by jianghaojun** [comment]
@TungWg Hi, I just upload the split files hhh.

**Comment by jianghaojun** [comment]
Where did you find them?

**Comment by TungWg** [comment]
I found them in detection_results.tar.
