### ISSUE TITLE
Pseudo-Q can train an epoch much faster than TransVG, why is the training time shortened?

### ISSUE THREAD

**Issue by linhuixiao** [LeapLabTHU/Pseudo-Q#9]
Hello, I want to ask you a question. In the process of Pseudo-Q replication, we found that for [the same fully supervised dataset] (yes, the same, fully), Pseudo-Q can train an epoch much faster than TransVG (about faster 5~6 times). I compared the codes of the two, but did not find the reason. Why is the training time shortened?

**Comment by jianghaojun** [comment]
@linhuixiao I didn't notice this phenomenon before. Could you please give me more details about this experiments?

**Comment by jianghaojun** [comment]
@linhuixiao Did you find the reason for this phenomenon?

From my perspective, Pseudo-Q adds a multi-level cross-modal attention into TransVG. Thus, I think the original TransVG might be faster than ours.
